In [13]:
from IPython.display import HTML
HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
Код для цього блокноту захований.Щоб подивитися або заховати знову код, тисніть
 <a href="javascript:code_toggle()">тут</a>.''')

In [1]:
import pandas as pd
import numpy as np
#pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.options.display.float_format = '{:,}'.format

#### нужно получить распредение населения по возрастным группам
#### 0-17, 18-60, 61 и старше в разрезе мужчин и женщин. Необходимо прогнозное
#### количество женщин детородного возраста, чтобы по регулируемому показателю 
#### фертильности, получить прогноз всего населения Украины.
#### Далее, зная фертильность и количество детей, можно спрогнозировать расходы
#### которые должно взять на себя государство, чтобы увеличилась рождаемость.

#### Таблиця 1. Історичні демографічні данні по Україні за 2008-2018 рік.

In [18]:
#исторические данные
#http://database.ukrcensus.gov.ua/MULT/Dialog/statfile_c_files/pasport.files/pasport/00_uk.htm#0301
#http://database.ukrcensus.gov.ua/PXWEB2007/ukr/publ_new1/2018/zb_dy_2017.pdf


naselennya_vse=pd.Series([46372664,46143714,45962947,45778534,45633637,45553047,45426249,42929298,42760516,42584542,42386403],\
                         index=list(np.arange(2008,2019)),name='Населення України')
miske_nas=pd.Series([31668757,31587203,31524795,31441649,31380874,31378639,31336623,29673113,29584952,29482313,29370995],\
                    index=list(np.arange(2008,2019)),name='Міське населення')
silske_nas=pd.Series([14703907,14556511,14438152,14336885,14252763,14174408,14089626,13256185,13175564,13102229,13015408],\
                     index=list(np.arange(2008,2019)),name='Сільське населення')

zhivonar=pd.Series([510589,512525,497689,502595,520705,503657,465882,411781,397037,363987],\
                   index=list(np.arange(2008,2018)),name='Живонароджених')
zhivonar_m=pd.Series([263588,264844,256835,259433,268748,259738,240043,212846,205194,187528],\
                    index=list(np.arange(2008,2018)),name='Живонароджених чоловіків')
zhivonar_f=pd.Series([247001,247681,240854,243162,251957,243919,225839,198935,191843,176459],\
                    index=list(np.arange(2008,2018)),name='Живонароджених жінок')
zhivonar_na_1000_nas=pd.Series([11.0,11.1,10.8,11.0,11.4,11.1,10.8,10.7,10.3,9.4],\
                               index=list(np.arange(2008,2018)),name='Живонароджених на 1000 населення')

mertvonar_all=pd.Series([3416,3351,3300,3158,3230,3166,2820,2437,2244,2136],\
                       index=list(np.arange(2008,2018)),name='Мертвонароджених')
mertvonar_m=pd.Series([1801,1821,1719,1649,1734,1683,1502,1322,1159,1090],\
                     index=list(np.arange(2008,2018)),name='Мертвонароджених чоловіків')
mertvonar_f=pd.Series([1615,1530,1581,1509,1496,1483,1318,1115,1085,1046],\
                     index=list(np.arange(2008,2018)),name='Мертвонароджених жінок')                    
                   

pomerlyh=pd.Series([754460,706739,698235,664588,663139,662368,632296,594796,583631,574123],\
                   index=list(np.arange(2008,2018)),name='Померлих')
pomer_na_1000_nas=pd.Series([16.3,15.3,15.2,14.5,14.5,14.6,14.7,14.9,14.7,14.5],\
                            index=list(np.arange(2008,2018)),name='Померлих на 1000 населення')



#https://ukrstat.org/uk/operativ/operativ2018/ds/mr/mr_u/mr1218_u.html
#Міграційний приріст, скорочення (–)
#[2011,2012,2013,2014,2015,2016,2017]
migraciya=pd.Series([17096,61844,31913,22592,14233,10620,11997],\
                    index=list(np.arange(2011,2018)),name='Міграційний приріст, скорочення (–)')
ukrstat=pd.concat([naselennya_vse,miske_nas,silske_nas,zhivonar,zhivonar_m,zhivonar_f,zhivonar_na_1000_nas,\
         mertvonar_all,mertvonar_m,mertvonar_f,pomerlyh,pomer_na_1000_nas,migraciya],axis=1).T
#ukrstat.to_excel('Данні_Укрстату_2008_2018.xlsx')

In [28]:
import qgrid
qgrid.show_grid(ukrstat,show_toolbar=True)

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defau…

In [15]:
from IPython.display import FileLink
FileLink("data/gdp.xlsx")

D:\Users\o.lukasevych\Documents\Python_Scripts\Ukr_budget\slide5_7\data\gdp.xlsx

Джерела: 
* "Демографічний паспорт -  Україна": *http://database.ukrcensus.gov.ua/MULT/Dialog/statfile_c_files/pasport.files/pasport/00_uk.htm#0301*
* "Населення України за 2017 рік.Демографічний щорічник.":
*http://database.ukrcensus.gov.ua/PXWEB2007/ukr/publ_new1/2018/zb_dy_2017.pdf
* "Міграційний рух населення" :
*https://ukrstat.org/uk/operativ/operativ2017/ds/mr/mr_u/mr1217_u.html

In [15]:
pop=pd.read_excel('data/pop_per_year.xlsx')
pop #с 2012 по 2018 по годам жизни мужчины и женщины

      рік  вік  Обидві статі    жінки   чоловіки
0    2012    0        498975   241656     257319
1    2012    1        493356   239066     254290
2    2012    2        507656   245582     262074
3    2012    3        505325   244779     260546
4    2012    4        467005   227066     239939
5    2012    5        455095   221946     233149
6    2012    6        420822   204201     216621
7    2012    7        422104   205168     216936
8    2012    8        403225   196289     206936
9    2012    9        384845   186452     198393
10   2012   10        369864   179530     190334
11   2012   11        380938   185080     195858
12   2012   12        385536   187741     197795
13   2012   13        409571   200455     209116
14   2012   14        427214   208388     218826
15   2012   15        461601   225189     236412
16   2012   16        479618   234009     245609
17   2012   17        498888   243185     255703
18   2012   18        528571   258075     270496
19   2012   19        569467   277969     291498
20   2012   20        610911   297944     312967
21   2012   21        642654   313646     329008
22   2012   22        673409   329231     344178
23   2012   23        717141   350939     366202
24   2012   24        741708   363051     378657
25   2012   25        786701   385941     400760
26   2012   26        763694   375600     388094
27   2012   27        780792   383957     396835
28   2012   28        793319   389940     403379
29   2012   29        723255   354493     368762
..    ...  ...           ...      ...        ...
537  2018   51        555788   296697     259091
538  2018   52        548667   295429     253238
539  2018   53        571144   309729     261415
540  2018   54        607217   332060     275157
541  2018   55        618382   340567     277815
542  2018   56        639060   352807     286253
543  2018   57        658082   365746     292336
544  2018   58        623390   350588     272802
545  2018   59        613864   347866     265998
546  2018   60        582590   333426     249164
547  2018   61        574648   332184     242464
548  2018   62        530112   309794     220318
549  2018   63        539149   318175     220974
550  2018   64        485976   290001     195975
551  2018   65        501423   302232     199191
552  2018   66        493016   298194     194822
553  2018   67        481354   293508     187846
554  2018   68        488077   302423     185654
555  2018   69        400651   249945     150706
556  2018   70        347745   220123     127622
557  2018   71        330123   212546     117577
558  2018   72        213082   139598      73484
559  2018   73        237472   158533      78939
560  2018   74        208152   140106      68046
561  2018   75        259397   176816      82581
562  2018   76        335004   227786     107218
563  2018   77        328293   225131     103162
564  2018   78        334278   234596      99682
565  2018   79        331301   234156      97145
566  2018   80       1677902  1214299     463603

[567 rows x 5 columns]

In [4]:
#коэффициенты відтворення та міграції по мужчинам и женщинам
#выделены из файлы модели, нужно сделать отдельными сериями,чтобы не привязываться к файлам
koef_vidtvorennya_nas_f=pd.read_excel('data/Copy of Демографическая модель изменения населения Украины.xlsx',\
                                     sheet_name='Sheet1')['відтворення населення жінки']
koef_vidtvorennya_nas_m=pd.read_excel('data/Copy of Демографическая модель изменения населения Украины.xlsx',\
                                     sheet_name='Sheet1')['відтворення населення чоловіка']
koef_mizhnar_saldo_f=pd.read_excel('data/Copy of Демографическая модель изменения населения Украины.xlsx',\
                                     sheet_name='Sheet1')['міжнародне сально жінки']
koef_mizhnar_saldo_m=pd.read_excel('data/Copy of Демографическая модель изменения населения Украины.xlsx',\
                                     sheet_name='Sheet1')['міжнародне сальдо чоловіка']

In [5]:
# коэффициенты по модели 2012 года,в 
#koef_zhyvonar=99.3835113134263 #коэффициент живорожденных от рожденных
#koef_mertvonar=0.616488686573717 #коэффициент мертворожденных от родженных
#koef_pomer=1.45894635287282 #коэффициент умерших от всего населения

#koef_usogo_nar_f=48.3748938322502 #коэффициент всего рожденных женщин
#koef_zhivonar_f=48.3876667210801 #коэффициент живорожденных женщин
#koef_mertvonar_f=46.3157894736842 #коэффициент мертворожденных женщин
#koef_pomer_f=50.9026011137936 #коэффициент умерших женщин

  #коэффициенты по мужчинам
#koef_usogo_nar_m=51.6251061677498
#koef_zhivonar_m=51.6123332789199
#koef_mertvonar_m=53.6842105263158
#koef_pomer_m=49.0973988862064

    #коэффициенты миграции
#koef_migrant_f=30.6820386779639
#koef_migrant_m=69.3179613220361

In [6]:
#считаем коеф по данным 2017 года:

narodzhennyh=zhivonar+mertvonar_all
narodzhennyh.name='Народженних'
koef_zhyvonar=zhivonar[2017]/narodzhennyh[2017]*100
koef_mertvonar=mertvonar_all[2017]/narodzhennyh[2017]*100
koef_pomer=pomerlyh[2017]/naselennya_vse[2017]*100

#коэффициенты по женщинам
koef_usogo_nar_f=(zhivonar_f[2017]+mertvonar_f[2017])/narodzhennyh[2017]*100#коэффициент всего рожденных женщин
koef_zhivonar_f= zhivonar_f[2017]/narodzhennyh[2017]*100#коэффициент живорожденных женщин
koef_mertvonar_f= mertvonar_f[2017]/narodzhennyh[2017]*100#коэффициент мертворожденных женщин
koef_pomer_f=50.9026011137936 #коэффициент умерших женщин

#коэффициенты по мужчинам
koef_usogo_nar_m=100-koef_usogo_nar_f
koef_zhivonar_m=100-koef_zhivonar_f
koef_mertvonar_m=100-koef_mertvonar_f
koef_pomer_m=49.0973988862064

#коэффициенты миграции
koef_migrant_f=30.6820386779639
koef_migrant_m=69.3179613220361

In [7]:
# на входе функции серия женщин по годам жизни,серия мужчины по годам жизни,
# кол-во детей на 1000 женщин,коеффициент миграции
def model(f_years,m_years,koef_fert,koef_migrant):
    popTotal=f_years.sum()+m_years.sum()
    fertilnyh=f_years[18:50].sum()
    narodzhennyh=fertilnyh*koef_fert/1000
    zhivonarodzhennyh=narodzhennyh*koef_zhyvonar/100
    mertvonarodzhennyh=narodzhennyh*koef_mertvonar/100
    pomer=popTotal*koef_pomer/100
    
    all_data=pd.Series({'fertilnyh':fertilnyh,'narodzhennyh':narodzhennyh,\
    'zhivonarodzhennyh':zhivonarodzhennyh,\
    'mertvonarodzhennyh':mertvonarodzhennyh,\
    'pomer':pomer})
    
    #количества по женщинам за текущий год
    usogo_nar_f=narodzhennyh*koef_usogo_nar_f/100 #всего рожденных женщин
    zhivonar_f=koef_zhivonar_f/100*zhivonarodzhennyh #количество живорожденных женщин
    mertvonar_f=koef_mertvonar_f/100*mertvonarodzhennyh #количество мертворожденных женщин
    pomer_f=koef_pomer_f/100*pomer #количество умерших женщин
    
    data_f=pd.Series({'usogo_nar_f':usogo_nar_f,'zhivonar_f':zhivonar_f,\
                      'mertvonar_f':mertvonar_f,'pomer_f':pomer_f})#для проверки
    
    #количества по мужчинам за текущий год
    zhivonar_m=koef_zhivonar_m/100*zhivonarodzhennyh
    usogo_nar_m=narodzhennyh*koef_usogo_nar_m/100
    mertvonar_m=koef_mertvonar_m/100*mertvonarodzhennyh
    pomer_m=koef_pomer_m/100*pomer
    
    data_m=pd.Series({'usogo_nar_m':usogo_nar_m,'zhivonar_m':zhivonar_m,\
                     'mertvonar_m':mertvonar_m,'pomer_m':pomer_m})#для проверки
    
    #серии відтворення населення
    vidtvorennya_nas_f=pd.Series(pomer_f*koef_vidtvorennya_nas_f/100*(-1))
    vidtvorennya_nas_m=pd.Series(pomer_m*koef_vidtvorennya_nas_m/100*(-1))
    
    # серии мигрантов
    migrant=popTotal*koef_migrant/100
    migrant_f=migrant*koef_migrant_f/100
    migrant_f_years=pd.Series(koef_mizhnar_saldo_f*migrant_f/100)
    migrant_m=migrant*koef_migrant_m/100
    migrant_m_years=pd.Series(koef_mizhnar_saldo_m*migrant_m/100)
    
    # серии женщин следующего года по годам жизни
    rest1=f_years[:-1]
    rest2=vidtvorennya_nas_f.drop(0).reset_index(drop=True)
    rest3=migrant_f_years.drop(0).reset_index(drop=True)
    rest1=rest1.astype('float64')
    rest4=rest1+rest2+rest3
    rest4=rest4[:-1]
    rest_first=zhivonar_f+vidtvorennya_nas_f[0]+migrant_f_years[0]
    rest_last=pd.Series(f_years.iloc[-1]+f_years.iloc[-2]+\
                vidtvorennya_nas_f.iloc[-1]+\
                migrant_f_years.iloc[-1])
    rest=rest4.append(rest_last).reset_index(drop=True)
    rest.index=rest.index+1
    rest_f=pd.concat([rest, pd.Series(rest_first)])
    female_next=rest_f.sort_index()
    
    rest_series=pd.Series({'rest':rest,'rest1':rest1,\
                           'rest2':rest2,'rest3':rest3,\
                           'rest4':rest4,\
                           'rest_first':rest_first,'rest_last':rest_last})
    
    # серии мужчин следующего года по годам жизни
    mrest1=m_years[:-1]
    mrest2=vidtvorennya_nas_m.drop(0).reset_index(drop=True)
    mrest3=migrant_m_years.drop(0).reset_index(drop=True)
    mrest1=mrest1.astype('float64')
    mrest4=mrest1+mrest2+mrest3
    mrest4=mrest4[:-1]
    mrest_first=zhivonar_m+vidtvorennya_nas_m[0]+migrant_m_years[0]
    mrest_last=pd.Series(m_years.iloc[-1]+m_years.iloc[-2]+\
                vidtvorennya_nas_m.iloc[-1]+\
                migrant_m_years.iloc[-1])
    mrest=mrest4.append(mrest_last).reset_index(drop=True)
    mrest.index=mrest.index+1
    rest_m=pd.concat([mrest, pd.Series(mrest_first)])
    male_next=rest_m.sort_index()
    pop_next=female_next+male_next
    pop_next_total=pop_next.sum()
    
     
    
    return female_next,male_next,pop_next_total,vidtvorennya_nas_f

In [8]:
def prognos_male(year,f_years,m_years,kfert):
    z=[]
    z_m=[]
    ye=[]
    pop_total=f_years.sum()+m_years.sum()
    for i in range(len(kfert)):
        fy=model(f_years,m_years,kfert[i],0.136060581939936)[0]
        my=model(f_years,m_years,kfert[i],0.136060581939936)[1]
        pt=model(f_years,m_years,kfert[i],0.136060581939936)[2]
        z.append(model(f_years,m_years,kfert[i],0.136060581939936)[0])
        z_m.append(model(f_years,m_years,kfert[i],0.136060581939936)[1])
        f_years=fy
        m_years=my
        pop_total=pt
        ye.append(year+1+i)
        
    return pd.DataFrame(z_m,ye).T

In [9]:
def prognos_female(year,f_years,m_years,kfert):
    z=[]
    z_m=[]
    ye=[]
    pop_total=f_years.sum()+m_years.sum()
    for i in range(len(kfert)):
        fy=model(f_years,m_years,kfert[i],0.136060581939936)[0]
        my=model(f_years,m_years,kfert[i],0.136060581939936)[1]
        pt=model(f_years,m_years,kfert[i],0.136060581939936)[2]
        z.append(model(f_years,m_years,kfert[i],0.136060581939936)[0])
        z_m.append(model(f_years,m_years,kfert[i],0.136060581939936)[1])
        f_years=fy
        m_years=my
        pop_total=pt
        ye.append(year+1+i)
        
    return pd.DataFrame(z,ye).T

In [10]:
pop2017=pop[pop['рік']==2017]#исходный факт
pop2017.head(2)

      рік  вік  Обидві статі   жінки   чоловіки
405  2017    0        394626  190833     203793
406  2017    1        408645  197600     211045

In [11]:
f=pop2017[' жінки'].reset_index(drop=True)
m=pop2017[' чоловіки'].reset_index(drop=True)

kfert_good=np.insert(np.repeat(95,25),[0],[38,60,70,80,95,95,95,95])


#прогнозы с 2018 года по 2050 с постоянным уровнем фертильности 2017 года 
#-37.93 -"Народилося в Україні на 1000 жінок дітородного віку"
pr_f=prognos_female(2017,f,m,np.repeat(37.93,33))
pr_m=prognos_male(2017,f,m,np.repeat(37.93,33))
pr_nas_bad=pr_f.sum()+pr_m.sum()

#прогнозы с 2018 года по 2050 с возрастающим уровнем фертильности 2017 года 
# до 95 "Народилося в Україні на 1000 жінок дітородного віку"
opt_f=prognos_female(2017,f,m,kfert_good)
opt_m=prognos_male(2017,f,m,kfert_good)
pr_nas_good=opt_f.sum()+opt_m.sum()

In [12]:
world_pop=pd.read_csv("data/WPP2017_TotalPopulationBySex.csv")

In [13]:
wpop_subset=world_pop[(world_pop.Location=='World')&(world_pop.Time>=2020)&\
                      (world_pop.Time<=2050)&(world_pop.Variant=='Medium')].PopTotal

wpop_subset.index=np.arange(2020,2051)
wpop_5=wpop_subset.iloc[::5]/1000
wpop_5.name='Населення світу, млн.осіб'
wpop_5

2020   7795.48
2025   8185.61
2030   8551.20
2035   8892.70
2040   9210.34
2045   9504.21
2050   9771.82
Name: Населення світу, млн.осіб, dtype: float64

In [14]:
#как есть прогноз
ukrpop_5=pr_nas_bad.loc[2020:].iloc[::5]/1000000
ukrpop_5.name='Населення України, млн.осіб'

f1849_5=pr_f.iloc[18:50,:].sum().loc[2020:].iloc[::5]/1000000
f1849_5.name='Жінок дітородного віку(18-49) в Україні, млн.осіб'
f1849_5

child_5=(pr_f+pr_m).iloc[0:18,:].sum().loc[2020:].iloc[::5]/1000000
child_5.name='Дітей(0-17) в Україні, млн.осіб'

m_f_5=(pr_m.iloc[18:61,:].sum()+pr_f.iloc[50:61,:].sum()).loc[2020:].iloc[::5]/1000000
m_f_5.name='Чоловіки(18-60) та жінки(50-60) в Україні, млн.осіб'

old_5=(pr_f+pr_m).iloc[61:,:].sum().loc[2020:].iloc[::5]/1000000
old_5.name='Населення від 61 року в Україні, млн.осіб'

kfert_5=pd.Series(np.repeat(37.93,7),index=[2020,2025,2030,2035,2040,2045,2050])
kfert_5.name='Народилося в Україні на 1000 жінок дітородного віку,осіб'

prognos_asis=pd.concat([wpop_5,ukrpop_5,f1849_5,child_5,kfert_5,m_f_5,old_5],axis=1).T
#prognos_asis.to_excel('Прогноз_какесть_2017.xlsx')

ukrpop_5-(f1849_5+child_5+m_f_5+old_5)#проверка

2020   0.00
2025   0.00
2030   0.00
2035   0.00
2040   0.00
2045   0.00
2050   0.00
dtype: float64

In [15]:
#хороший прогноз
ukrpop_5_good=pr_nas_good.loc[2020:].iloc[::5]/1000000
ukrpop_5_good.name='Населення України, млн.осіб'
child_5=(opt_f+opt_m).iloc[0:18,:].sum().loc[2020:].iloc[::5]/1000000
child_5.name='Дітей(0-17) в Україні, млн.осіб'

f1849_5=opt_f.iloc[18:50,:].sum().loc[2020:].iloc[::5]/1000000
f1849_5.name='Жінок дітородного віку(18-49) в Україні, млн.осіб'
m_f_5=(opt_m.iloc[18:61,:].sum()+opt_f.iloc[50:61,:].sum()).loc[2020:].iloc[::5]/1000000
m_f_5.name='Чоловіки(18-60) та жінки(50-60) в Україні, млн.осіб'

old_5=(opt_f+opt_m).iloc[61:,:].sum().loc[2020:].iloc[::5]/1000000
old_5.name='Населення від 61 року в Україні, млн.осіб'

good_koef=pd.Series(kfert_good,index=np.arange(2018,2051)).loc[2020:].iloc[::5]
good_koef.name='Народилося в Україні на 1000 жінок дітородного віку,осіб'

prognos_good=pd.concat([wpop_5,ukrpop_5_good,f1849_5,child_5,good_koef,m_f_5,old_5],axis=1).T
#prognos_good.to_excel('Прогноз_хороший_2017.xlsx')

ukrpop_5_good-(f1849_5+child_5+m_f_5+old_5)#проверка

2020   -0.00
2025    0.00
2030    0.00
2035   -0.00
2040   -0.00
2045    0.00
2050    0.00
dtype: float64